### ISSUE TITLE
Moving this up in the curriculum

### ISSUE THREAD

**Issue by AnnJohn** [learn-co-curriculum/skills-based-javascript-intro-to-flow-control#1]
Can we move this up to before functions? And then have parts of the operators lesson as a lesson before this?

The one thing that this lab does cover though that is only covered in functions are return values, but we could update that to not be return. Or we can mention return values earlier. 

I feel like this before functions seems to be an easier order for students because the structures are a less complicated. But just a suggestion. 

@jmburges

**Comment by pletcher** [comment]
Yeah, I'm down with that.

**Comment by pletcher** [comment]
And in this case, I wonder if we can let them understand what it means for an expression (in the `if` statements, for example) to "return" something before introducing them to what it means for functions to `return` in the next section?

**Comment by AnnJohn** [comment]
actually yeah i like that idea, re: just keeping the lab as is with return statements there
