### ISSUE TITLE
test\index.test.js missing line 1-4 from learn.co

### ISSUE THREAD

**Issue by tjasonnguyen** [learn-co-curriculum/skills-based-javascript-intro-to-flow-control#15]
in the learn.co, it said 
"At the very top of the file, you'll see"

`const expect = require('expect')
const fs = require('fs')
const jsdom = require('mocha-jsdom')
const path = require('path')`

But on the IDE file, it's missing these lines on test\index.test.js

**Comment by aturkewi** [comment]
Hey @tjasonnguyen I'm looking at the README for this lab, and I'm not seeing it called out anywhere that a `test/index.js` file should have that at the top. Was that perhaps from a previous readme?

If you do look in the [test file](https://github.com/learn-co-curriculum/skills-based-javascript-intro-to-flow-control/blob/master/test/flow-control-test.js) for this lab though, there is a `flow-control-test.js` file in there and that does have those lines. 

I'm going to close this out, but if I've misunderstood this, please feel free to re-open the issue and let me know where you are seeing that text.
