### ISSUE TITLE
switchAge function in test

### ISSUE THREAD

**Issue by emmaadams** [learn-co-curriculum/skills-based-javascript-intro-to-flow-control#17]
For this problem of the test: 
"Define a function switchAge that accepts an age as a parameter. The case statement should switch on age and return "You are a teenager" if the age is 13, 14, 15, 16, 17, 18, or 19, and return "You have an age" as the default."
A switch statement does not work in IDE, however, an if statement does. The way the instructions are worded, it sounds as if ONLY a switch statement should be used. I am not sure if this is an issue in IDE or a wording error. I learned a lot in the process of trying to solve this though so I do appreciate that. 
Thank you for your time.

This was the statement that eventually passed:
`function switchAge(age){
  if (age <= 19 && age >= 13){
    return ("You are a teenager"); }
  else
    {return ("You have an age"); }
  }`

This is what I had initially attempted (along with 3 hours of tinkering and minor changes) that had not passed:
`function switchAge(age){
  switch(age) {
  case "age <= 19 && age >= 13": 
    return "You are a teenager"
  default: 
  return "You have an age"
}`

**Comment by AnnJohn** [comment]
hi @emmaadams  we updated the lesson and specs so this should be fixed. thanks!
