### ISSUE TITLE
test error result has capitalization typo that leads to incorrect entry of code .

### ISSUE THREAD

**Issue by AlexanderNelson** [learn-co-curriculum/skills-based-javascript-intro-to-flow-control#18]
the 1st line of the returned error shows "you are not a teenager" where as the actual expected return is "You are not a teenager"
![flow-control typo](https://cloud.githubusercontent.com/assets/16615147/17906974/9bd5e6dc-6947-11e6-8a3a-403da8635bd7.PNG)

**Comment by AnnJohn** [comment]
also should be fixed
