### ISSUE TITLE
test error statement contradicts expected result

### ISSUE THREAD

**Issue by AlexanderNelson** [learn-co-curriculum/skills-based-javascript-intro-to-flow-control#19]
The 1st line of the error states the return should be "You are not a teenager"
The expected result is "You have an age"
![test typo2](https://cloud.githubusercontent.com/assets/16615147/17913826/f434f69c-696a-11e6-851c-dd806f49d659.PNG)

**Comment by AnnJohn** [comment]
hi @AlexanderNelson we updated the lesson and specs so this should be fixed. thanks!
