### ISSUE TITLE
issue with the lab

### ISSUE THREAD

**Issue by jlew826** [learn-co-curriculum/skills-based-javascript-intro-to-flow-control#2]
after opening the lab, and running the test before working on the lab:

![screen shot 2016-06-28 at 4 51 53 pm](https://cloud.githubusercontent.com/assets/18472624/16431992/242bbd7c-3d51-11e6-8723-0ff38ce0d0c9.png)

The flow-control.js looks like:
![screen shot 2016-06-28 at 4 52 09 pm](https://cloud.githubusercontent.com/assets/18472624/16432011/429603f8-3d51-11e6-8fb9-8f9003f659f1.png)

**Comment by pletcher** [comment]
Thanks for being a part of the Learn community!

Keep in mind that this space is for specific issues related to the content of this lesson.

If you're reporting on the content of this lesson, it'd be super helpful if you could include a stack trace of any errors that you're seeing.

If you'd like to report a bug about the Learn IDE, the Ask a Question form, opening a file, or the lights not working on Learn, please report a bug directly on https://learn.co. (You can find the bug report form by clicking on your avatar in the upper right, and then selecting "Report A Bug".)

We want to respond as quickly as possible and be as helpful as possible, so please be sure to include steps to reproduce the issue (as best you can remember) and any pertinent details about your environment. (Are you using the Learn IDE? Coding from the ISS?) We'll figure out what's up and get back to you ASAP.

**Comment by pletcher** [comment]
Fixed with 980730e4a67fac86155c3d33a7d52fa3a63a833b, thanks!
