### ISSUE TITLE
Lab does not open in IDE

### ISSUE THREAD

**Issue by Maui21** [learn-co-curriculum/skills-based-javascript-intro-to-flow-control#22]
The flow-controls lab will run in the console when I click "open" but nothing will open in the IDE. No file appears in the sidebar so I cannot edit or run any code.

![flow-control screenshot](https://cloud.githubusercontent.com/assets/21348088/18142812/2f3d9ea6-6f8d-11e6-8223-b770f3fdbde1.png)

**Comment by AnnJohn** [comment]
hi @Maui21 could you please use Ask a Question and someone from our team will help you out? Also could you file a bug report as well? If you click on your profile pic in Learn, you'll see a menu with an option to Report a Bug. Thanks!
