### ISSUE TITLE
the 

### ISSUE THREAD

**Issue by nrajendran2** [learn-co-curriculum/skills-based-javascript-intro-to-flow-control#26]
the flow-control.js file has disappeared. I was given lackluster advice to delete the rest of the text from the text editor and to replace it later. Since I did that, I have had a ruby error when I do "learn" in the terminal.  I was just advised to resync the folder. I did so, closed the LEARN IDE program, reopened and now that folder is gone.

**Comment by AnnJohn** [comment]
hi @nrajendran2 sorry for the trouble. Since this looks like a problem specific to you, could you use Ask a Question in Learn and someone from our team will help you troubleshoot and resolve the issue. thanks!
