### ISSUE TITLE
Finding that no matter what it doesnt pass through.

### ISSUE THREAD

**Issue by JimmyBonez** [learn-co-curriculum/skills-based-javascript-intro-to-flow-control#27]

**Comment by JimmyBonez** [comment]
Also with the ternary you shouldn't pass a return to it, kept giving me an error on console. So I believe that is broken or my brain is broken on all of this.

**Comment by AnnJohn** [comment]
hi @JimmyBonez could you use Ask a Question and someone will help you out with your code and work through the tests? Thanks!
