### ISSUE TITLE
Learn Giving Errors

### ISSUE THREAD

**Issue by victttorious** [learn-co-curriculum/skills-based-javascript-intro-to-flow-control#28]
Hello, I have been trying to complete this lab, but I keep getting errors on code that I believe should work.
It is telling me syntax error near token. Even when I put in a basic function which will work in my browser such as 
function sayHelloTo(name) {
 console.log(`Hello, ${name}!`)
  } 
sayHelloTo('Isabel') <-- written in console
instead of returning "Hello, Isabel!"
it will give me BASH- syntax error near token 'Isabel'
I am not quite sure what is wrong.
I have tried writing in other files/labs and I continue to get the same errors.

**Comment by AnnJohn** [comment]
hi @victttorious could you use Ask a Question and someone will help you out right away as this looks like it's an issue with you code and not the lab itself. thanks!
