### ISSUE TITLE
Small glitch

### ISSUE THREAD

**Issue by proyceus** [learn-co-curriculum/skills-based-javascript-intro-to-flow-control#34]
I was doing this lesson yesterday and quit it out halfway through. I started to continue doing the exercise today and tried submitting the code in the Learn IDE but it would not accept any of the tests even though they were all correct. Even the ones that were checked off yesterday when testing were not being accepted. I tried reopening a new file in Learn IDE but it would not work. Even tried to cut and paste and alter some of the code in Learn IDE but that didn't work. Pretty disappointing.

**Comment by gj** [comment]
Hi @proyceus,

If you're still having trouble with this, check out the Ask a Question feature on the Learn website!

**Comment by aturkewi** [comment]
Hey @proyceus 

Thanks for taking a look at our curriculum! @gj has the right idea here though. To get help with this error that you're getting, you want to log into learn.co and use the Ask A Question button. This section is really meant for when the tests were written incorrectly and it is not possible to pass the lab. I think the tests are correct here but it looks like you may need to modify your code or there might be an issue with your Learn IDE and syncing. Head on over to the Ask a Question button and we'll be more than happy to lend a hand and help get this sorted! We have Learn Experts on every day from 9am to 1am EDT.
