### ISSUE TITLE
question about this flow control lesson..

### ISSUE THREAD

**Issue by realproto** [learn-co-curriculum/skills-based-javascript-intro-to-flow-control#37]
What is wrong with the last function of switchAge? 
 switchAge('20') should return the default answer but this Learn system sees the string `You are a teenager`?  The rest of my code passes but this the one error I cannot get passed.

function switchAge(age) {
 switch(age) { case "13": return `You are a teenager`; case "14": return `You are a teenager`; case "15": return `You are a teenager`; case "16": return `You are a teenager`; case "17": return `You are a teenager`; case "18": return `You are a teenager`; case "19": return `You are a teenager`; default: return `You have an age`; break};
}

**Comment by JessRudder** [comment]
If you are still having an issue, please use the "Ask a Question" feature to get help from Learn experts.
