### ISSUE TITLE
Tests Do Not Find Code I've Written

### ISSUE THREAD

**Issue by greghelton** [learn-co-curriculum/skills-based-javascript-intro-to-flow-control#39]
I run command `learn test` and I get errors saying function not found.

<img width="1113" alt="screen shot 2016-12-15 at 2 14 45 pm" src="https://cloud.githubusercontent.com/assets/32062/21240739/325dc1c2-c2d2-11e6-8589-d12af81e93d1.png">

**Comment by greghelton** [comment]
Ran just `learn` and tests failed with same errors

**Comment by JessRudder** [comment]
Hi @greghelton this usually means that you either haven't defined the function (perhaps there's a typo in the name) OR you have a syntax error that is preventing the compiler from reading that section of code.
