### ISSUE TITLE
Learn IDE not loading

### ISSUE THREAD

**Issue by sheena213** [learn-co-curriculum/skills-based-javascript-intro-to-flow-control#53]
I have restarted my learn IDE app, browser, and laptop several times and can't get the IDE to load properly. I'm not able to type anything in the terminal. I'm connected to wireless internet, so I am out of ideas as to what could possibly be going on. Is this a common issue? Any advice on how to troubleshoot?

Thanks,
Sheena

**Comment by JessRudder** [comment]
@sheena213 if you are still experiencing issues, please use the "Ask a Question" feature on Learn to get live help from a Learn Expert.
