### ISSUE TITLE
ReferenceError: basicTeenager is not defined at Context.it (test/flow-control-test.js:26:14) 

### ISSUE THREAD

**Issue by natelee3** [learn-co-curriculum/skills-based-javascript-intro-to-flow-control#54]
Have not been able to pass any tests although my code matches multiple passing submissions. I get the "not defined" error for each test.

**Comment by indigoes** [comment]
I am having the same issue - what can be done to resolve this?

**Comment by natelee3** [comment]
Mine was a syntax issue-- accidentally deleted a curly brace. Check your code [here](https://repl.it/languages/javascript)
