### ISSUE TITLE
Reference Error in test file

### ISSUE THREAD

**Issue by Moocow89** [learn-co-curriculum/skills-based-javascript-intro-to-flow-control#58]
I am getting a ReferenceError in the flow-control-test.js file for the Javascript flow-control assignment.

 1) flow-control basicTeenager should return "You are a teenager!" if the age is between 13
-19:                                                                                        
     ReferenceError: basicTeenager is not defined                                           
      at Context.it (test/flow-control-test.js:26:14) 

This error happens for all of the function that file tests. I'm not sure why this is coming up because I'm not even supposed to touch that file in the challenge.

**Comment by indigoes** [comment]
Same issue - did you find a resolution?

**Comment by Moocow89** [comment]
@indigoes Yes, I did. So even though the error is saying there is a problem with the test file it is actually just a problem in your code. You have to figure out what you did wrong in your code and it will pass. Unfortunately this error is no help in actually helping you figure out what is wrong with your code.
