### ISSUE TITLE
Flow Control

### ISSUE THREAD

**Issue by savannahday99** [learn-co-curriculum/skills-based-javascript-intro-to-flow-control#59]
Every time I try to run a test by typing learn or anything for that matter, I get this...
"You don't appear to be in a Learn lesson's directory. Please cd to an appropriate directory
 and try again."
What am I doing wrong?

**Comment by JessRudder** [comment]
@savannahday99 you need to make sure you are in the directory for the lesson that you are working on.  When you type `pwd` in the console, the output should match the directory of the lesson you're on.  If that's not the case, use the `cd` command to move into that directory (e.g. `cd javascript-lesson-1`)
