### ISSUE TITLE
JavaScript Flow control lab errors

### ISSUE THREAD

**Issue by TropintheBard** [learn-co-curriculum/skills-based-javascript-intro-to-flow-control#60]
every time I run the test, I recieve this error for every function
1) flow-control basicTeenager should return "You are a teenager!" if the age is between 13-19:                            
     ReferenceError: basicTeenager is not defined                                                                           
      at Context.it (test/flow-control-test.js:26:14)        
2) flow-control basicTeenager should return undefined if the age is not between 13-19:                                    
     ReferenceError: basicTeenager is not defined                                                                           
      at Context.it (test/flow-control-test.js:30:14)  

I think there is something wrong with the flow-control-test.js file 
but am I just an idiot?
here is my code for the lesson:

function basicTeenager(age) {
  if (age >= 13 && age <= 19){
    return "You are a teenager!"
  }
}

function teenager(age) {
  if (age >= 13 && age <= 19){
  return "You are a teenager!"
}
  else {
return "You are not a teenager"

  }

}

function ageChecker(age) {
if (age <= 12){
  return "You are a kid"
}
else if (age >= 13 && age <= 19) {
return "You are a teenager!"
}
else{
return "You are a grownup"}
}

function ternaryTeenager(age)
{
  (age >= 1 && age <= 19) ? return "You are a teenager": return "You are not a teenager"

}

function switchAge(age) {
switch(age){
  case (age >= 13 && age <=19):
  console.log("You are a teenager");
  break;
  default:
  console.log("You have an age");
}
}

**Comment by indigoes** [comment]
I'm having the same issue

**Comment by indigoes** [comment]
this is my new issue:

![image](https://cloud.githubusercontent.com/assets/25351222/23228592/2183e754-f90b-11e6-9910-6ad2e507a1e3.png)

**Comment by swallsy** [comment]
@indigoes Did you ever get it figured out? I was having difficulty but just figured it out using the following:  
<img width="864" alt="screen shot 2017-02-25 at 10 01 12 pm" src="https://cloud.githubusercontent.com/assets/19861044/23336730/1f3c7978-fba6-11e6-811c-94967bf553ca.png">

**Comment by BiggieT** [comment]
I'm having exactly the same issue as well :(
I might end up having to use a switch just to clear the lab.

**Comment by Riot69** [comment]
Here is how it is suppose to work...
function basicTeenager(age) {
if (age >= 13 && age <= 19){
return "You are a teenager!";
  }
}
function teenager(age) {
if (age >= 13 && age <= 19){
return "You are a teenager!";
} else {
return "You are not a teenager";}
}

function ageChecker(age) {
if (age >= 13 && age <= 19){
return "You are a teenager!";
} else if (age <=12) {
return "You are a kid";
} else {
return "You are a grownup"}}

function ternaryTeenager(age) {
if (age >= 13 && age <= 19) {
  return "You are a teenager";
} else { (age > 19 && age < 13)
  return "You are not a teenager";}
}

function switchAge(age) {
  if (age >= 13 && age <= 19) {
    return "You are a teenager";
} else { (age > 19 && age < 13)
  return "You have an age";}
}

**Comment by Apex-Code** [comment]
I did the lab a while ago, but the OP should consider using https://repl.it/languages/javascript to check for syntax errors.  As written, you're missing a few ";" and your ternary function is formatted incorrectly.  Throw an "if" in there and take out the ? and ":".  

For me it is easier to put the return on the next line.  If I don't do that, it makes it look jumbled/harder to read.  That's just me though, technically JS will understand it on the same line.

**Comment by tochi5027** [comment]
![image](https://cloud.githubusercontent.com/assets/12417723/24674389/cdcd68be-1940-11e7-86e9-7a6de9e9be38.png)

![image](https://cloud.githubusercontent.com/assets/12417723/24674417/ea5a427c-1940-11e7-8c57-5d06a1608fb0.png)

All these worked

**Comment by JessRudder** [comment]
Hi

The error that you're seeing is usually one of two things:

1) The function has not been defined.  Sometimes this could be a typo in the function name `basicTenager` vs `basicTeenager`.  Make sure to double check that the function definition is there and that it is named exactly the same as what the test is calling for.

2) There is a syntax error that is preventing the JavaScript compiler from reading the function (which means that function is not defined later when the code tries to call it).  

Try copying and pasting your code into the JavaScript console in Chrome to see if it shows any syntax errors.

**Comment by moniquetanon** [comment]
Are there any other reasons why this error might be appearing. I'm currently having this issue. I tested my first function out in the console and it's working with the correct outputs.

**Comment by mashuka** [comment]
had the same issues, turned out i done everything correctly but missed the closing } . watch out for typos and stuff

**Comment by NatashaSelvidge** [comment]
I am getting the same issue and I tested in the console and they all work except basicTeenager. In Learn, none of my functions are defined. Please Help!  
ReferenceError: basicTeenager is not defined

Here is my code. 


function basicTeenager(age) {
  if (age >=13 && age <=19) { 
    return "You are a teenager!";
 }
}


function teenager(age) {
if (age >= 13 && age <= 19){
return "You are a teenager!";
} else {
return "You are not a teenager";}
}

function ageChecker(age) {
if (age >= 13 && age <= 19){
return "You are a teenager!";
} else if (age <=12) {
return "You are a kid";
} else {
return "You are a grownup"}}

function ternaryTeenager(age) {
if (age >= 13 && age <= 19) {
return "You are a teenager";
} else { (age > 19 && age < 13)
return "You are not a teenager";}
}

function switchAge(age) {
  switch(age){
case 13:
return "You are a teenager"
case 14:
return "You are a teenager"
case 15:
return "You are a teenager"
case 16:
return "You are a teenager"
case 17:
return "You are a teenager"
case 18:
return "You are a teenager"
case 19:
return "You are a teenager"

default:
return "You have an age"
  }
}
