### ISSUE TITLE
Having trouble with JS Flow Control Lab.  See Code below

### ISSUE THREAD

**Issue by klj310** [learn-co-curriculum/skills-based-javascript-intro-to-flow-control#64]
function basicTeenager(age) {
  if (age >= 13 && age <= 19){
  return You are a teenager!
}
}

}

function teenager(age) {
  if (age >= 13 && age <= 19){
  return You are a teenager!
} else {
  return You are not a teenager
}

}

function ageChecker(age) {
  if (age >= 13 && age <= 19){
  return You are a teenager!
} else if (age <=12) {
  return You are a kid
} else {
  return You are a grownup
}

}

function ternaryTeenager(age) {return conditionToTest (age >= 13 && age <= 19) You are a teenager : You are not a teenager

}

function switchAge(age) {
  switch(age) {
    case "13":
      console.log("You are a teenager");
      break;
      case "14":
        console.log("You are a teenager");
        break;
      case "15":
          console.log("You are a teenager");
          break;
      case "16":
          console.log("You are a teenager");
          break;
      case "17":
          console.log("You are a teenager");
          break;
      case "18":
          console.log("You are a teenager");
          break;
      case "19":
          console.log("You are a teenager");
          break;
      default:
        console.log("You have an age")

**The errors for everything say "ReferenceError: basicTeenager is not defined" "ReferenceError: teenager is not defined", etc.  What am I missing?**

**Comment by JessRudder** [comment]
Hi @klj310 

The error that you're seeing is usually one of two things:

1) The function has not been defined.  Sometimes this could be a typo in the function name `basicTenager` vs `basicTeenager`.  Make sure to double check that the function definition is there and that it is named exactly the same as what the test is calling for.

2) There is a syntax error that is preventing the JavaScript compiler from reading the function (which means that function is not defined later when the code tries to call it).

Try copying and pasting your code into the JavaScript console in Chrome to see if it shows any syntax errors.
