### ISSUE TITLE
IDE not working right

### ISSUE THREAD

**Issue by claytoncrockett** [learn-co-curriculum/skills-based-javascript-intro-to-flow-control#65]
I'm pretty confident my code is correct (seen here: http://imgur.com/a/t4C4k) but it wont pass the learn test.  What should I do?

**Comment by claytoncrockett** [comment]
![desktop 02 26 2017 - 15 03 25 01](https://cloud.githubusercontent.com/assets/25967674/23344302/5a562bf8-fc37-11e6-97b7-7446736c6871.png)

**Comment by RubbrDucky** [comment]
it appears it is not saving properly.

I have the same issue.

**Comment by JessRudder** [comment]
@claytoncrockett from the screenshot it looks like you did not save your file.  The tests can only run against code that has been saved.  If you're still having an issue, please use the "Ask a Question" feature to get live help from a Learn Expert.
