### ISSUE TITLE
Answers for Control Flow Lab not checking

### ISSUE THREAD

**Issue by bparikh82** [learn-co-curriculum/skills-based-javascript-intro-to-flow-control#69]
Hello, I am trying to run learn test and it gives me an undefine error for every single one. Is it possible that the original coding to check is messed up?

**Comment by JessRudder** [comment]
Hi @bparikh82 

The error that you're seeing is usually one of two things:

1) The function has not been defined.  Sometimes this could be a typo in the function name `basicTenager` vs `basicTeenager`.  Make sure to double check that the function definition is there and that it is named exactly the same as what the test is calling for.

2) There is a syntax error that is preventing the JavaScript compiler from reading the function (which means that function is not defined later when the code tries to call it).

Try copying and pasting your code into the JavaScript console in Chrome to see if it shows any syntax errors.
