### ISSUE TITLE
Stuck on the Syntax of this Lab. 

### ISSUE THREAD

**Issue by SidewaysReptile** [learn-co-curriculum/skills-based-javascript-intro-to-flow-control#70]
function basicTeenager(age) {
  if(age >= 13 && age <= 19) {
    return "You are a teenager!"
  }
}

This is my code, when I run a test, it returns an error message saying basicTeenager is not defined. I thought I defined it with (age) and made the comparison in the next line. Any thoughts on what I am doing wrong?

**Comment by JessRudder** [comment]
Hi @SidewaysReptile  

The error that you're seeing is usually one of two things:

1) The function has not been defined.  Sometimes this could be a typo in the function name `basicTenager` vs `basicTeenager`.  Make sure to double check that the function definition is there and that it is named exactly the same as what the test is calling for.

2) There is a syntax error that is preventing the JavaScript compiler from reading the function (which means that function is not defined later when the code tries to call it).

Try copying and pasting your code into the JavaScript console in Chrome to see if it shows any syntax errors.
