### ISSUE TITLE
Not enough guidance to complete lab

### ISSUE THREAD

**Issue by NeenaGit** [learn-co-curriculum/skills-based-javascript-intro-to-flow-control#71]
Hello I'm currently on the "javascript flow-control page". As a beginner, I'm finding it difficult to complete the "flow-control" lab, since there isn't enough info on the lesson on how to properly define a function in order to create the "if else" statements.

Thanks.

**Comment by JessRudder** [comment]
@NeenaGit you can use the "Ask a Question" feature in Learn to get help from Learn Experts if you need more detail.
