### ISSUE TITLE
Javascript  Functions Lab

### ISSUE THREAD

**Issue by tochi5027** [learn-co-curriculum/skills-based-javascript-intro-to-flow-control#74]
Hi I wrote the following functions for the Javascript functions lab but keep getting a 'not defined' error. At least the first one looks correct

function happyHolidays() {
 return "Happy Holidays!"
 }

 function happyHolidaysTo(name) {
 return `Happy Holidays, ${name}!`
 }

 function happyHolidayTo(holiday, name) {
  return `Happy ${holiday}, ${name}!`

function holidayCountdown(holiday, days) {
  return `It's ${days} until ${holiday}!`
}
 

However all tests still fail with the error messages:
0 passing (2s)                                                         
  4 failing                                                              
                                                                         
  1) functions happyHolidays returns "Happy holidays!":                  
     ReferenceError: happyHolidays is not defined                        
      at Context.it (test/index-test.js:6:14)                            
                                                                         
  2) functions happyHolidaysTo(name) returns "Happy holidays, ${name}!": 
     ReferenceError: happyHolidaysTo is not defined                      
      at Context.it (test/index-test.js:12:14)                           
                                                                         
  3) functions happyHolidayTo(holiday, name) returns "Happy ${holiday}, $
{name}!":                                                                
     ReferenceError: happyHolidayTo is not defined                       
      at Context.it (test/index-test.js:18:14)                           
   
4) functions holidayCountdown(holiday, days) returns "It's ${days} unti
l ${holiday}!":                                                          
     ReferenceError: holidayCountdown is not defined                     
      at Context.it (test/index-test.js:24:14)

**Comment by devonjboen** [comment]
You've probably fixed this by now, but for the first one, you need to lowercase holidays. Right now you have "Happy Holidays!" It needs to be "Happy holidays!"

**Comment by JessRudder** [comment]
Hi @tochi5027  

The error that you're seeing is usually one of two things:

1) The function has not been defined.  Sometimes this could be a typo in the function name `basicTenager` vs `basicTeenager`.  Make sure to double check that the function definition is there and that it is named exactly the same as what the test is calling for.

2) There is a syntax error that is preventing the JavaScript compiler from reading the function (which means that function is not defined later when the code tries to call it).

Try copying and pasting your code into the JavaScript console in Chrome to see if it shows any syntax errors.
