### ISSUE TITLE
unable to load Learn IDE

### ISSUE THREAD

**Issue by KTAcampora** [learn-co-curriculum/skills-based-javascript-intro-to-flow-control#75]
Learn IDE not able to load JS Flow Control Lab. Quit in the middle of a test

**Comment by KTAcampora** [comment]
Seems like system is down... now, not responding at all. Please advise

**Comment by JessRudder** [comment]
@KTAcampora if this issue hasn't been resolved, please use the "Ask a Question" feature in Learn to get live help from a Learn Expert.
