### ISSUE TITLE
for some reason the code is not running / passing tests even after checking the syntax...

### ISSUE THREAD

**Issue by snigdhasur** [learn-co-curriculum/skills-based-javascript-intro-to-flow-control#76]
function teenager(age) {
  if (age <= 19 && age >= 13) {
    return "You are a teenager!"
  } else {
    return "You are not a teenager!"
  }
}

**Comment by JessRudder** [comment]
@snigdhasur please use the "Ask a Question" feature in Learn to get live help from a Learn Expert.
