### ISSUE TITLE
lab

### ISSUE THREAD

**Issue by Jaquin92** [learn-co-curriculum/skills-based-javascript-intro-to-flow-control#78]
I am certain my functions are correct and they are coming up undefined

**Comment by JessRudder** [comment]
Hi @Jaquin92  

The error that you're seeing is usually one of two things:

1) The function has not been defined.  Sometimes this could be a typo in the function name `basicTenager` vs `basicTeenager`.  Make sure to double check that the function definition is there and that it is named exactly the same as what the test is calling for.

2) There is a syntax error that is preventing the JavaScript compiler from reading the function (which means that function is not defined later when the code tries to call it).

Try copying and pasting your code into the JavaScript console in Chrome to see if it shows any syntax errors.
