### ISSUE TITLE
Lab + README with no Instruction for Lab

### ISSUE THREAD

**Issue by aviflombaum** [learn-co-curriculum/skills-based-javascript-intro-to-flow-control#83]
This seems to be a README explaining some flow control techniques as well as a lab. The Lab's instruction are basically hidden int he test suite which is hard to read. I'd seperate the lab from the README and take the Lab and add instructions on what methodology to use in each test.

**Comment by gj** [comment]
Will take this into account in structuring the new control flow content. Thanks!
